### ISSUE TITLE
how to get access to the version number in the build ? 

### ISSUE THREAD

**Issue by maxandersen** [toolebox-io/gradle-git-versioner#13] opened 2019-12-25 02:10 UTC
project.version evaluates to "unspecified" - is there a way to get access to the version from within build.gradle ?

**Comment by Tyrannoseanus** [comment] 2019-12-25 11:48
The version isn't set until the project is evaluated- beforehand it will be unspecified. 

If you wrap whatever you need to access the version from in a project.afterEvaluate block, you should be able to access the calculated version.

**Comment by maxandersen** [comment] 2019-12-25 13:54
Ok I’ll try ;)

**Comment by maxandersen** [comment] 2019-12-25 16:02
:/ tried tons of different ways now and all fail...got an example of how to do get the version value ? 

I'm basically trying to copy some files which needs the project.version to have correct values filtered in.

**Comment by maxandersen** [comment] 2019-12-25 16:03
also, afterEvaluate seems too late to actually do something that affects the build...

**Comment by maxandersen** [comment] 2019-12-26 07:14
figured it out and leaving it here for anyone else in same situation :)

```
task homebrew(type: Copy) {
    project.afterEvaluate {
        from('src/main/scripts/jbang.rb')
        into(buildDir.toString() + '/brew/formula')
        filter(ReplaceTokens,
                tokens: [
                'projectVersion': project.version,
                'sha256': new File(distZip.outputs.files[0].path + ".sha256").text
                        ]
        )
    }
}

createChecksum.dependsOn(assembleDist)
homebrew.dependsOn(createChecksum)
build.dependsOn(homebrew)
```

basically just setup proper task dependencies and then put the actual copying with filtering inside a `project.afterEvaluate` then it works ;)

**Comment by Tyrannoseanus** [comment] 2020-03-24 19:17
Apologies for the late reply to this Max. Are you still having trouble? 

I had a go at this recently and couldn't reproduce the problem. Could you go into a little more information of what you're trying to do? 

For what it's worth, I've done some testing and it should be possible to do anything you need to do, as long as you defer version discovery until after the project has been evaluated. This can either be in a `project.afterEvaluate` call if you need it at configuration time, or if you have your own task you can just access the version during task execution and it will be populated by that point. For example: 

```
task version() {
    println project.version // prints unspecified - this is too early in the configuration phase
    project.afterEvaluate {
        println project.version // prints version - configuration stage but late enough to be calculated
    }
    doFirst {
        println project.version // prints version - execution stage, so late enough to be calculated
    }
    doLast {
        println project.version // prints version - execution stage, so late enough to be calculated
    }
}
```

You mentioned copying files. Depending on exactly what you're trying to do this should be possible. For example: 

```
task copy(type: Copy) {
    from "."
    into "build"
    include "README.md"
    filter { line -> line.replaceAll("%VERSION", project.version) }
}
```

This will copy the README and replace all occurrences of `%VERSION` with the correctly calculated version. This is because the project.version is inside the filter closure which is deferred until task execution, at which point the version has been calculated. 

If you're not working inside a closure this can happen at configuration time and be too early, leading to an `unspecified` version. 

```
task copy(type: Copy) {
    from "."
    into "build"
    rename("README.md", "${project.version}-README.md")
    include "README.md"
    filter { line -> line.replaceAll("%VERSION", project.version) }
}
```

This won't work and will copy it into `unspecified-README.md` instead of the correct file. In this case you have to wrap it in a `project.afterEvaluate` so the version is calculated in time. Something like: 
```
task copy(type: Copy) {
    project.afterEvaluate {
        from "."
        into "build"
        include "README.md"
        rename("README.md", "${project.version}-README.md")
        filter { line -> line.replaceAll("%VERSION", project.version)
        }
    }
}
```
This will work. So will wrapping up only the "rename" in `project.afterEvaluate`. 

There might be other scenarios that I haven't tested though. 

You might not need this any more so I'll close the issue with this comment and re-open if you need any more guidance on this. 

Should probably add some of this information to the README too.

**Closed as completed by Tyrannoseanus** 2020-03-24 19:17 UTC

**Comment by maxandersen** [comment] 2020-03-26 08:12
thank you for the details - I actually ended up doing it similar to your suggestion here but it just felt as quite a hack :) but if that’s the way i'm all good. Good to have it documented!

**Comment by AnakinPt** [comment] 2020-04-29 08:30
I saw this plugin before, https://github.com/qoomon/gradle-git-versioning-plugin, can't we do something similar? The way they run, the version is the first thing to do.

**Comment by Tyrannoseanus** [comment] 2020-04-29 09:46
🤔 

That's not a bad idea. It'd mean making the configuration active rather than passive and might mean a breaking change if I can't figure out how to make it work both ways. But it would solve these problems and be really obvious when the version is available rather than relying on Gradle phases.
